### ISSUE TITLE
Try to compile on fedora 37 but error on libtool 2.4.6

### ISSUE THREAD

**Issue by peterborto** [Pavel-Sayekat/ByteOnPanel#1]
Hi, how can i solve this error?

/bin/sh ../libtool  --tag=CC   --mode=link gcc  -g -O2   -o byteonpanel byteonpanel.o  -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lcairo   
libtool: Version mismatch error.  This is libtool 2.4.6 Debian-2.4.6-9, but the
libtool: definition of this LT_INIT comes from libtool 2.4.6.42-b88ce.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.6 Debian-2.4.6-9
libtool: and run autoconf again.

I try to compile in fedora 37.
Thank you

**Comment by Pavel-Sayekat** [comment]
![Screenshot_fedora-live_2023-05-24_16:44:35](https://github.com/Pavel-Sayekat/ByteOnPanel/assets/17138178/f4cd6314-17a2-417d-a77c-cbee7f869d43)
The byteonpanel running on fedora38 with i3 wm in the above picture.

Try removing the aclocal.m4 file and then run  "aclocal"
& run" libtoolize --force"
& run "autoreconf "
& run "automake --add-missing" and then run ./configure followed by make.

**Comment by peterborto** [comment]
Hi Pavel,
thank you for reply.
I've also Fedora 38.
I try and found error:

aclocal


#libtoolize --force
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.

**Comment by peterborto** [comment]
Update:

libtoolize --force
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
[root@port-bortoletto ByteOnPanel-master]# autoreconf
configure.ac:15: warning: The macro `AC_PROG_LIBTOOL' is obsolete.
configure.ac:15: You should run autoupdate.
m4/libtool.m4:100: AC_PROG_LIBTOOL is expanded from...
configure.ac:15: the top level
configure.ac:21: warning: The macro `GLIB_GNU_GETTEXT' is obsolete.
configure.ac:21: You should run autoupdate.
aclocal.m4:388: GLIB_GNU_GETTEXT is expanded from...
aclocal.m4:488: AM_GLIB_GNU_GETTEXT is expanded from...
configure.ac:21: the top level
configure.ac:21: warning: The macro `AC_TRY_LINK' is obsolete.
configure.ac:21: You should run autoupdate.
./lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
aclocal.m4:73: GLIB_LC_MESSAGES is expanded from...
aclocal.m4:388: GLIB_GNU_GETTEXT is expanded from...
aclocal.m4:488: AM_GLIB_GNU_GETTEXT is expanded from...
configure.ac:21: the top level
configure.ac:21: warning: The macro `AC_TRY_LINK' is obsolete.
configure.ac:21: You should run autoupdate.
./lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/headers.m4:89: _AC_CHECK_HEADER_COMPILE is expanded from...
./lib/autoconf/headers.m4:56: AC_CHECK_HEADER is expanded from...
aclocal.m4:172: GLIB_WITH_NLS is expanded from...
aclocal.m4:388: GLIB_GNU_GETTEXT is expanded from...
aclocal.m4:488: AM_GLIB_GNU_GETTEXT is expanded from...
configure.ac:21: the top level
configure.ac:21: warning: The macro `AC_TRY_LINK' is obsolete.
configure.ac:21: You should run autoupdate.
./lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/headers.m4:89: _AC_CHECK_HEADER_COMPILE is expanded from...
./lib/autoconf/headers.m4:56: AC_CHECK_HEADER is expanded from...
aclocal.m4:172: GLIB_WITH_NLS is expanded from...
aclocal.m4:388: GLIB_GNU_GETTEXT is expanded from...
aclocal.m4:488: AM_GLIB_GNU_GETTEXT is expanded from...
configure.ac:21: the top level
configure.ac:21: warning: The macro `AC_OUTPUT_COMMANDS' is obsolete.
configure.ac:21: You should run autoupdate.
./lib/autoconf/status.m4:1025: AC_OUTPUT_COMMANDS is expanded from...
aclocal.m4:172: GLIB_WITH_NLS is expanded from...
aclocal.m4:388: GLIB_GNU_GETTEXT is expanded from...
aclocal.m4:488: AM_GLIB_GNU_GETTEXT is expanded from...
configure.ac:21: the top level
configure.ac:12: error: required file './compile' not found
configure.ac:12:   'automake --add-missing' can install 'compile'
configure.ac:5: error: required file './missing' not found
configure.ac:5:   'automake --add-missing' can install 'missing'
src/Makefile.am: error: required file './depcomp' not found
src/Makefile.am:   'automake --add-missing' can install 'depcomp'
autoreconf: error: automake failed with exit status: 1

#automake --add-missing
configure.ac:12: installing './compile'
configure.ac:5: installing './missing'
src/Makefile.am: installing './depcomp'

**Comment by peterborto** [comment]
Probably go fine any way i see in accessories menu and the if i lunch it 
![immagine](https://github.com/Pavel-Sayekat/ByteOnPanel/assets/129761996/0442a89d-2c4c-4481-8e18-61cf10e1b058)

a small icon appear on the try BAR.

My DE is LXDE, probably better integration with Gnome :)

**Comment by Pavel-Sayekat** [comment]
BTW, no need to do all those as root, you just need to run "sudo make install" after a successful make. Also you can set byteonpanel to auto start using start up application settings. And it works fine with i3, lxde, xfce and mate, didn't test it on gnome3. Also I meant by showing the screenshot that if it works on fedora38, it will definitely work on fedora37.
